### ISSUE TITLE
Merge Partition and HivePartition objects

### ISSUE THREAD

**Issue by SamRoberts** [CommBank/maestro#293] opened 2015-01-09 00:54 UTC
At the moment, the factory functions for `Partition` are split into two objects: `Partition` and `HivePartition`. The `HivePartition` partitions have a different `path` value, but we never actually use that anyway. We should merge `Partition` and `HivePartition`.

**Comment by stephanh** [comment] 2015-03-14 02:49
Duplicate of #276.

**Closed by stephanh** 2015-03-14 02:49 UTC
