### ISSUE TITLE
GC overhead limit exceeded error in Load step while processing 200+ files in a single run

### ISSUE THREAD

**Issue by AnnTomie** [CommBank/maestro#479] opened 2016-02-08 06:52 UTC
**Background :**
A SAP load job expects more than 300 files to be loaded in an hour during exceptional scenarios ( regression, error generated in upstream). In normal scenario, job is expecting only around 10 files to be processed. When number of files to be processed is more than 150, load step of the job fails with GC overhead limit exceeded error . After implementing  ```Oom``` fix  recently, we were able to gracefully load 200 files in a single batch as compared to former . When replicated the issue in local, it succeeded due to the increased memory available when compared to DS.

Exception thrown during job failure when it ran with 250 files:
```
16/02/05 14:50:04 INFO flow.Flow: [] starting
16/02/05 14:50:04 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0080/2015/11/10/16/34/17"]
16/02/05 14:50:04 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/2247f892-a57b-4204-b526-ecea1b4b8144.seq"]
16/02/05 14:50:04 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:04 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:04 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:04 INFO flow.FlowStep: [] starting step: (1/1) ...204-b526-ecea1b4b8144.seq
16/02/05 14:50:05 INFO Upload: Starting fileUploads
16/02/05 14:50:05 INFO Upload: Starting fileUploads
16/02/05 14:50:06 INFO flow.Flow: [] starting
16/02/05 14:50:06 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0049/2015/09/21/17/22/53"]
16/02/05 14:50:06 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/84387657-159d-4598-a92f-6e38fa860b61.seq"]
16/02/05 14:50:06 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:06 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:06 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:06 INFO flow.FlowStep: [] starting step: (1/1) ...598-a92f-6e38fa860b61.seq
16/02/05 14:50:06 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:06 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:06 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:06 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:06 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:06 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:06 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:06 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:06 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:06 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:06 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:06 INFO Upload: Starting fileUploads
16/02/05 14:50:06 INFO Upload: Starting fileUploads
16/02/05 14:50:06 INFO Upload: Starting fileUploads
16/02/05 14:50:07 INFO Upload: Starting fileUploads
16/02/05 14:50:07 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:07 INFO flow.Flow: [] starting
16/02/05 14:50:07 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0051/2015/09/21/17/00/28"]
16/02/05 14:50:07 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/bc5240a7-d97e-4b0b-9ce1-65fdb5480bbb.seq"]
16/02/05 14:50:07 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:07 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:07 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:07 INFO flow.FlowStep: [] starting step: (1/1) ...b0b-9ce1-65fdb5480bbb.seq
16/02/05 14:50:07 INFO flow.Flow: [] starting
16/02/05 14:50:07 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0005/2015/11/03/11/29/18"]
16/02/05 14:50:07 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/19b9e8c1-488b-4ca5-874c-441ffae8a569.seq"]
16/02/05 14:50:07 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:07 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:07 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:07 INFO flow.Flow: [] starting
16/02/05 14:50:07 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0052/2015/11/10/16/48/07"]
16/02/05 14:50:07 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/d59a8565-29e6-4b00-9f8d-b4c3b4c275bd.seq"]
16/02/05 14:50:07 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:07 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:07 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:07 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:07 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:08 INFO flow.FlowStep: [] starting step: (1/1) ...b00-9f8d-b4c3b4c275bd.seq
16/02/05 14:50:08 INFO flow.Flow: [] starting
16/02/05 14:50:08 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0038/2015/09/21/16/58/58"]
16/02/05 14:50:08 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/7863797a-babb-4f38-8440-7a2089a9545c.seq"]
16/02/05 14:50:08 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:08 INFO flow.FlowStep: [] starting step: (1/1) ...ca5-874c-441ffae8a569.seq
16/02/05 14:50:08 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:08 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:08 INFO flow.FlowStep: [] starting step: (1/1) ...f38-8440-7a2089a9545c.seq
16/02/05 14:50:13 INFO Upload: Copied EMP_20151103111900_0040_SRM_HREMP_20151103-113517-393.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0040/2015/11/03/11/35/17 
16/02/05 14:50:13 INFO Upload: Upload ended
16/02/05 14:50:14 INFO Upload: Copied EMP_20151103111900_0031_SRM_HREMP_20151103-113338-389.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0031/2015/11/03/11/33/38 
16/02/05 14:50:14 INFO Upload: Upload ended
16/02/05 14:50:14 INFO Upload: Copied EMP_20151110145415_0078_SRM_HREMP_20151110-165357-841.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0078/2015/11/10/16/53/57 
16/02/05 14:50:14 INFO Upload: Upload ended
16/02/05 14:50:14 INFO Upload: Copied EMP_20151110145415_0076_SRM_HREMP_20151110-165357-920.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0076/2015/11/10/16/53/57 
16/02/05 14:50:14 INFO Upload: Upload ended
16/02/05 14:50:14 INFO Upload: Copied EMP_20151103111900_0027_SRM_HREMP_20151103-113256-497.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0027/2015/11/03/11/32/56 
16/02/05 14:50:14 INFO Upload: Upload ended
16/02/05 14:50:14 INFO Upload: Copied EMP_20150916165243_0026_SRM_HREMP_20150921-160714-344.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0026/2015/09/21/16/07/14 
16/02/05 14:50:14 INFO Upload: Upload ended
16/02/05 14:50:14 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20151103111900_0040_SRM_HREMP_20151103-113517-393.dat
16/02/05 14:50:14 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20151110145415_0076_SRM_HREMP_20151110-165357-920.dat
16/02/05 14:50:14 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20151110145415_0078_SRM_HREMP_20151110-165357-841.dat
16/02/05 14:50:18 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:18 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:18 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:18 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:19 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20150916165243_0026_SRM_HREMP_20150921-160714-344.dat
16/02/05 14:50:19 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20151103111900_0027_SRM_HREMP_20151103-113256-497.dat
16/02/05 14:50:19 INFO Upload: Copied EMP_20150914172624_0032_SRM_HREMP_20150918-141948-535.dat to /dev/source/sapcrm/glas/FEEDBACK/EMP_0032/2015/09/18/14/19/48 
16/02/05 14:50:19 INFO Upload: Upload ended
16/02/05 14:50:19 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20151103111900_0031_SRM_HREMP_20151103-113338-389.dat
16/02/05 14:50:19 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:19 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:19 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:19 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:19 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:20 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:20 INFO glas.FeedbackLoadExecution$: File uploaded /disk1/bigdata/dev/dataFeed/sapcrm/EMP_20150914172624_0032_SRM_HREMP_20150918-141948-535.dat
16/02/05 14:50:20 INFO flow.Flow: [] starting
16/02/05 14:50:20 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0040/2015/11/03/11/35/17"]
16/02/05 14:50:20 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/f561e45b-3d3a-4132-8cfc-2d96f479bf6c.seq"]
16/02/05 14:50:20 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:20 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:20 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:20 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:20 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:20 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:20 INFO flow.Flow: [] starting
16/02/05 14:50:20 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0078/2015/11/10/16/53/57"]
16/02/05 14:50:20 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/5f899db9-6b80-475f-a363-323144539800.seq"]
16/02/05 14:50:20 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:20 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:20 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:20 INFO flow.FlowStep: [] starting step: (1/1) ...132-8cfc-2d96f479bf6c.seq
16/02/05 14:50:21 INFO flow.FlowStep: [] starting step: (1/1) ...75f-a363-323144539800.seq
16/02/05 14:50:21 INFO flow.Flow: [] starting
16/02/05 14:50:21 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0026/2015/09/21/16/07/14"]
16/02/05 14:50:21 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/93bbdb31-7c16-47f0-87bd-f1c9b3a3e6b5.seq"]
16/02/05 14:50:21 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:21 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:21 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:21 INFO flow.FlowStep: [] starting step: (1/1) ...7f0-87bd-f1c9b3a3e6b5.seq
16/02/05 14:50:21 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:21 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:21 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:21 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:21 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:21 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:21 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:21 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
16/02/05 14:50:21 INFO util.HadoopUtil: using default application jar, may cause class not found exceptions on the cluster
16/02/05 14:50:21 INFO planner.HadoopPlanner: using application jar: /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/etl-sapcrm-glas-assembly-2.0.0-20151129230126-bb3b6f9-SNAPSHOT.jar
16/02/05 14:50:21 INFO flow.Flow: [] starting
16/02/05 14:50:21 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0027/2015/11/03/11/32/56"]
16/02/05 14:50:21 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/b8ae5db3-01c5-4abc-961c-4272450b0dd1.seq"]
16/02/05 14:50:21 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:21 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:21 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:21 INFO flow.FlowStep: [] starting step: (1/1) ...abc-961c-4272450b0dd1.seq
16/02/05 14:50:23 INFO flow.Flow: [] starting
16/02/05 14:50:23 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0076/2015/11/10/16/53/57"]
16/02/05 14:50:23 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/4dd1218b-3208-4357-97a4-552a2287254a.seq"]
16/02/05 14:50:23 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:23 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:23 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:23 INFO flow.Flow: [] starting
16/02/05 14:50:23 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0032/2015/09/18/14/19/48"]
16/02/05 14:50:23 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/42d6f1a2-67ba-4ccf-9218-786b23cb5af6.seq"]
16/02/05 14:50:23 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:23 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:23 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:23 INFO flow.Flow: [] starting
16/02/05 14:50:23 INFO flow.Flow: []  source: Hfs["TextLine[['offset', 'line']->[ALL]]"]["/dev/source/sapcrm/glas/FEEDBACK/EMP_0031/2015/11/03/11/33/38"]
16/02/05 14:50:23 INFO flow.Flow: []  sink: Hfs["CombinedSequenceFileScheme[[0:1]]"]["/tmp/hadoop-acoe_omnds_dintg/maestro/a63a1c98-2e84-4ad6-85e3-9e465e2fe153.seq"]
16/02/05 14:50:23 INFO flow.Flow: []  parallel execution is enabled: true
16/02/05 14:50:23 INFO flow.Flow: []  starting jobs: 1
16/02/05 14:50:23 INFO flow.Flow: []  allocating threads: 1
16/02/05 14:50:23 INFO flow.FlowStep: [] starting step: (1/1) ...ccf-9218-786b23cb5af6.seq
16/02/05 14:50:24 INFO flow.FlowStep: [] starting step: (1/1) ...ad6-85e3-9e465e2fe153.seq
16/02/05 14:50:24 INFO flow.FlowStep: [] starting step: (1/1) ...357-97a4-552a2287254a.seq
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/java_pid8597.hprof ...
Heap dump file created [310900719 bytes in 35.403 secs]
Exception in thread "ResponseProcessor for block BP-196710065-10.37.40.241-1374176758914:blk_1353757363_1100047825233" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "DataStreamer for file /user/acoe_omnds_dintg/.staging/job_201601310350_21399/job.jar block BP-196710065-10.37.40.241-1374176758914:blk_1353757351_1100047825221" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "ResponseProcessor for block BP-196710065-10.37.40.241-1374176758914:blk_1353757362_1100047825232" java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos
at org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos$PipelineAckProto.internalGetFieldAccessorTable(DataTransferProtos.java:16396)
at com.google.protobuf.GeneratedMessage.getAllFieldsMutable(GeneratedMessage.java:105)
at com.google.protobuf.GeneratedMessage.getAllFields(GeneratedMessage.java:153)
at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:272)
at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:248)
at com.google.protobuf.TextFormat.shortDebugString(TextFormat.java:88)
at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.toString(PipelineAck.java:185)
at java.lang.String.valueOf(String.java:2847)
at java.lang.StringBuilder.append(StringBuilder.java:128)
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer$ResponseProcessor.run(DFSOutputStream.java:814)
Exception in thread "ResponseProcessor for block BP-196710065-10.37.40.241-1374176758914:blk_1353757366_1100047825236" java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos
at org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos$PipelineAckProto.internalGetFieldAccessorTable(DataTransferProtos.java:16396)
at com.google.protobuf.GeneratedMessage.getAllFieldsMutable(GeneratedMessage.java:105)
at com.google.protobuf.GeneratedMessage.getAllFields(GeneratedMessage.java:153)
at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:272)
at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:248)
at com.google.protobuf.TextFormat.shortDebugString(TextFormat.java:88)
at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.toString(PipelineAck.java:185)
at java.lang.String.valueOf(String.java:2847)
at java.lang.StringBuilder.append(StringBuilder.java:128)
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer$ResponseProcessor.run(DFSOutputStream.java:814)
Exception in thread "ResponseProcessor for block BP-196710065-10.37.40.241-1374176758914:blk_1353757351_1100047825221" java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos
at org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos$PipelineAckProto.internalGetFieldAccessorTable(DataTransferProtos.java:16396)
at com.google.protobuf.GeneratedMessage.getAllFieldsMutable(GeneratedMessage.java:105)
at com.google.protobuf.GeneratedMessage.getAllFields(GeneratedMessage.java:153)
at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:272)
at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:248)
at com.google.protobuf.TextFormat.shortDebugString(TextFormat.java:88)
at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.toString(PipelineAck.java:185)
at java.lang.String.valueOf(String.java:2847)
at java.lang.StringBuilder.append(StringBuilder.java:128)
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer$ResponseProcessor.run(DFSOutputStream.java:814)
Exception in thread "DataStreamer for file /user/acoe_omnds_dintg/.staging/job_201601310350_21394/job.jar block BP-196710065-10.37.40.241-1374176758914:blk_1353757320_1100047825190" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Heap Dump:**

/disk1/bigdata/dev/glas/KERBEROS/FEEDBACK/2.0.0-20151129230126-bb3b6f9-SNAPSHOT/java_pid8597.hprof

**Root Cause:**

From Heap dump it is quite evident, the major class eating up the memory is a Hash Map and it is not releasing the memory . Based on initial analysis of heap dump it seems hadoop configuration is getting piled up .The hash map is storing all hadoop configuration as keys and values which  is not getting cleared .

**Comment by vineethvarghese** [comment] 2016-02-08 22:33
hmm.. are you sure about it being hadoop config?

**Comment by AnnTomie** [comment] 2016-02-09 01:49
![screen shot 2016-02-09 at 12 40 57 pm](https://cloud.githubusercontent.com/assets/8380379/12905334/7ae0463c-cf2a-11e5-8ee6-9d24ef4d9ddb.png)

 Could see multiples hadoop job config details stored in the HashMap

**Comment by rowandavies** [comment] 2016-03-09 05:10
I had a look at the heap dump, and I think this is caused by the scalding execution cache.  If so, the solution will be to use `withSeparateCache` from https://github.com/CommBank/maestro/commit/c18183d74ce9f2d978e8fcce9b44ec9ce2593d6f see https://github.com/CommBank/maestro/pull/478  

Basically I suggest wrapping the execution for each group of files in `withSeparateCache`.  If I'm right about which job this is, I think this means adding it like below:

```
 def doPersist[H <: ThriftStruct : Decode : Tag : Manifest, T <: ThriftStruct : Decode : Tag : Manifest, D <: ThriftStruct : Decode : Tag : Manifest](
     grp: List[DataFile],
     feedbackTransformation: String => (T => D),
     conf: GlasFeedbackLoadConfig[H, T, D],
     etlLoadRun: LoadRun,
     logger: Logger
   ): Execution[Boolean] = (Execution.withSeparateCache(for {
    aggTaskStatus <- Execution.sequence(grp.map(loadData(_, conf, etlLoadRun, feedbackTransformation, logger)))
    collectStatus <- Execution.from { aggTaskStatus.collect{ case Some(info) => info}
                       .foldLeft((List[TypedPipe[H]](), List[LoadInfo](), List[TypedPipe[D]](), List[LoadInfo](), List[String]())) {
                          (acc, curr) => (curr.header :: acc._1, curr.hLoadInfo :: acc._2, curr.data :: acc._3, curr.dLoadInfo :: acc._4, curr.file :: acc._5)
                       }
                     }
    status        <- if(!collectStatus._2.exists(_.isInstanceOf[LoadFailure])  &&
                        !collectStatus._4.exists(_.isInstanceOf[LoadFailure]) &&
                        collectStatus._1.size != 0
                     ) {
                          loadViewHive(conf, collectStatus._1.reduce(_ ++ _), collectStatus._3.reduce(_ ++ _), etlLoadRun, collectStatus._5, logger)
                       }
                       else {
                           Execution.fail("LoadFailure exists or all files in the set are duplicate... Please investigate !!!!")
                       }
  } yield status)).onException(
    controlExec(conf)(_.failRun(etlLoadRun))
  )
```

Can you try this and then update this issue?

**Comment by bpbinumon** [comment] 2016-03-23 06:20
We have modified the code as suggested by @rowandavies  and successfully loaded 550 files in a single run.

**Comment by rowandavies** [comment] 2016-03-23 06:23
I think Ann mentioned that there was another issue though after making this change, where there was a failure in some cases involving duplicates that didn't happen prior to the change.  We could keep this issue open if that seems related, otherwise we could close this now.

**Comment by bpbinumon** [comment] 2016-03-23 06:46
We have analysed more on that issue and found that it was not related to the memory problem  and happy to close this.
In our code, we  were using maestro  error folder for moving the duplicate files and the ACLs on that folder caused that issue which Ann mentioned.

**Closed** 2016-03-28 23:52 UTC
