### ISSUE TITLE
I need the ability to validate the file based on the header/trailer records

### ISSUE THREAD

**Issue by jamindaw** [CommBank/maestro#31] opened 2014-04-14 07:49 UTC
In certain loads, we use the row count  from the trailer record to validate the file.

**Comment by stephanh** [comment] 2015-03-14 03:16
With the execution monad it is now possible to validate a file based row counts provided elsewhere. The only part that is still missing is good support for parsing header and trailer records which is raised in #32.

Since the outstanding work is just a duplicate of #32. I'm going to close this issue.

**Closed by stephanh** 2015-03-14 03:16 UTC
Labels: enhancement
