### ISSUE TITLE
Javac compilation error while executing Parlour import from Maestro

### ISSUE THREAD

**Issue by JosephShobin** [CommBank/maestro#310] opened 2015-01-22 22:24 UTC
If the project contains more than 25 objects(more number of table imports) , while executing jar in actual environment throws javac compilation error.
All unit test cases are working and compilation is success, 
If we separate/ remove some of the objects from the code, it works as expected.

**Comment by greyamigo** [comment] 2015-01-23 05:33
This error occurs even if there are large number of dependencies in build.sbt .
 A project exporting into only one table and project contining less than 10 classes can also fail if there are like lot of dependency jars ( teradata jdbc, teradata driver , oracle driver and scalikejdbc) thus increasing the number of classes

**Comment by JosephShobin** [comment] 2015-01-23 06:51
@greyamigo : That might be the problem, in my case there is oracle and scalikejdbc dependencies in build.sbt and i need both these dependencies.

**Comment by anukrishnank** [comment] 2015-01-27 03:36
Teradata parlor import  facing same issue even if the project contains less table to import (5 tables in my case).The project contains 4 additional dependencies in build.sbt ( org.scalikejdbc, com.ncr.teradata, com.ncr.teradata, com.cloudera.connector) .I think the issue is with the large number of class files present in the jar and not with the number of tables to import

**Comment by SamRoberts** [comment] 2015-01-27 03:49
thanks everyone for the reports. @greyamigo and @anukrishnank , can you please email me a link to the commit in your projects which faces this issue?

**Comment by SamRoberts** [comment] 2015-01-27 05:15
@JosephShobin looking at the two new projects which have faced this issue, it seems that the sub-project workaround I have been working on probably isn't a good idea. It won't help if the majority of classes come from dependencies, rather than a large number of executions. I am thinking I will put my work on the sub-project on hold, and get straight into debugging the issue at hand.

**Comment by JosephShobin** [comment] 2015-01-27 07:20
yes @SamRoberts sub-projecting is a temporary work around only, if we can fix the root cause then that is good.

**Comment by MadhuMi** [comment] 2015-01-28 03:06
@SamRoberts I was initially having 26 tables to import within one project .When it threw the javac error i split that project into two ,one containing only 10 table imports , but still i am facing the same issue.

**Comment by stephanh** [comment] 2015-01-28 03:45
Does this issue only occur when running the code on the cluster or also if local tests are run?

**Comment by SamRoberts** [comment] 2015-01-28 03:57
@MadhuMi thanks for that. I had stopped working on that workaround, but good to get another data point.

@stephanh Joseph reported that his tests work fine, it's only on the cluster that the issue arises. I'd be interested to see whether that is the case with the other projects. @greyamigo, @anukrishnank, and @MadhuMi: do your local tests work?

**Comment by anukrishnank** [comment] 2015-01-28 04:27
@SamRoberts Local test worked for me. The issue occurs when running the code in cluster

**Comment by jithinjohn** [comment] 2015-01-28 06:04
@SamRoberts @stephanh  we have also faced same issue with sqoop import ETL jobs when 34 table objects are created in same project

**Comment by OlassayilMinu** [comment] 2015-01-28 06:26
SQL server import facing the issue with import of 1 table.

**Comment by MadhuMi** [comment] 2015-01-28 08:11
@SamRoberts ..Yes ..My test is working fine .. Issue is only while running the jar

**Comment by SamRoberts** [comment] 2015-01-29 06:39
To everyone following this issue, we have noticed that @JosephShobin's project fails when the number of files in the jar crosses the limit of the number of files allowed with the zip format used in Java 6.

We are currently investigating whether reducing the number of files in the jar below this limit will fix the problem. If it does, we will fix shortly.

**Comment by SamRoberts** [comment] 2015-01-29 11:45
Update for people following this issue: reducing the number of class files in the jar below the limit did fix the problem. Once we have changed our assembly jar process so that it packages less files into the jar (there is lots of room for improvement here), we should have fixed the issue. We should be able to get a fix out in the next day or two that works for most projects: my main concern is whether it will be enough for the biggest projects.

I would like everyone who has faced this issue to run `jar -tf your_assembly.jar` and email me the results, please. I would like to know how many files we have to remove for each of your jars, and what sort of class files you each have in your jars.

**Comment by SamRoberts** [comment] 2015-02-02 02:19
Update for the people following this issue: there is a new version of etl-plugin which reduced the number of class files into the jar. This should fix your problems, but I would like for those affected to test it and let me know if there are any issues.

Can you please try running your assembly using etl-plugin version 0.6.0-20150202121956-01f994f, and let me know how that goes?

**Comment by MadhuMi** [comment] 2015-02-02 05:04
@SamRoberts ..I am able to run the project containing 17 sqoop import using new etl-plugin version

**Comment by SamRoberts** [comment] 2015-02-02 05:05
fantastic, thanks

**Comment by SamRoberts** [comment] 2015-02-02 22:34
It sounds like this is working for everyone.

There is still an open question as to whether @JosephShobin can get all 140 loads into the same project without causing issues, but his load is working right now. If that turns out to be a problem, we can create another issue for it (e.g. #317).

Closing.

**Closed by SamRoberts** 2015-02-02 22:34 UTC
